"""
Source separation with Demucs (htdemucs_6s).
Stems: drums, bass, guitar, piano, vocals, other

The model is downloaded automatically on first run (~2 GB).
Requires: pip install demucs
"""

import os
import tempfile
import shutil
import subprocess
from pathlib import Path

import numpy as np
import soundfile as sf

# Stem names from htdemucs_6s and their display labels
STEM_LABELS = {
    "drums":  "Drums",
    "bass":   "Bass",
    "guitar": "Guitar",
    "piano":  "Piano",
    "vocals": "Vocals",
    "other":  "Percussion / Other",
}

MODEL = "htdemucs_6s"
TARGET_SR = 22050


def separate(audio_path: str, device: str = "cpu") -> dict:
    """
    Separates audio into stems using Demucs.

    Args:
        audio_path: path to the original audio file (any format)
        device: "cpu" or "cuda" if a GPU is available

    Returns:
        dict {stem_name: np.ndarray mono float32 at TARGET_SR}
    """
    out_dir = tempfile.mkdtemp(prefix="music_coach_demucs_")
    try:
        _run_demucs(audio_path, out_dir, device)
        stems = _load_stems(out_dir, audio_path)
    finally:
        shutil.rmtree(out_dir, ignore_errors=True)
    return stems


def _run_demucs(audio_path: str, out_dir: str, device: str) -> None:
    """Runs Demucs as a subprocess."""
    cmd = [
        "python", "-m", "demucs",
        "-n", MODEL,
        "-d", device,
        "-o", out_dir,
        "--mp3",
        audio_path,
    ]
    print(f"     Running Demucs ({MODEL}) on {device}... this may take several minutes.")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"Demucs failed:\n{result.stderr[-2000:]}"
        )


def _load_stems(out_dir: str, audio_path: str) -> dict:
    """Loads the stems generated by Demucs as mono numpy arrays."""
    track_name = Path(audio_path).stem
    stems_dir = Path(out_dir) / MODEL / track_name

    if not stems_dir.exists():
        # Demucs sometimes uses a slightly different name
        candidates = list(Path(out_dir).rglob("*.mp3")) + list(Path(out_dir).rglob("*.wav"))
        if not candidates:
            raise FileNotFoundError(f"No stems found in {out_dir}")
        stems_dir = candidates[0].parent

    stems = {}
    for stem_name in STEM_LABELS:
        # Look for the stem file (mp3 or wav)
        for ext in (".mp3", ".wav"):
            stem_file = stems_dir / f"{stem_name}{ext}"
            if stem_file.exists():
                y, sr = sf.read(str(stem_file))
                if y.ndim > 1:
                    y = y.mean(axis=1)
                y = y.astype(np.float32)
                # Resample if needed
                if sr != TARGET_SR:
                    import librosa
                    y = librosa.resample(y, orig_sr=sr, target_sr=TARGET_SR)
                stems[stem_name] = y
                break

    if not stems:
        raise FileNotFoundError(f"No valid stems found in {stems_dir}")
    return stems
